export const ROUTER_PATH = {
  ROOT: '/',
  WELCOME: '/welcome',
  USER: '/user',
  GUIDELINE: '/guideline',
  JOURNEY_PREVIEW: '/preview',
  PREVENT: '/prevent/:id',
  COMMUNITY: '/community/:type',
  POST_DETAIL: '/community/:type/post',
  POSTING: '/community/post',
  PREVENT_RESULT: '/preventResult',
  NOT_FOUND: '*',
  LOGIN: 'login',
  CONSULTING: '/consulting',
  SURVEY: '/survey',
  DOCUMENT_FORM: '/documentForm',
  GUIDELINE_RESULT: '/guidelineResult',
  CONSULTING_HISTORY: '/consulting/consultingHistory',
} as const;
